{
 "title": "ASP.NET OT Metrics",
 "description": "Shows ASP.NET metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "opentelemetry",
  "otel",
  "prometheus",
  "process",
  "runtime",
  "httpclient",
  "aspnetcore"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "http_client_peer_name",
    "label": "HTTP Client Pear Name",
    "query": {
     "query": "label_values(http_client_duration_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"},net_peer_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_time_seconds_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_memory_usage_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_threads{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "General Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(process_runtime_dotnet_gc_committed_memory_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Committed Memory Size"
      },
      {
       "expr": "max_over_time(process_runtime_dotnet_gc_objects_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Objects Size"
      },
      {
       "expr": "irate(process_runtime_dotnet_gc_allocations_size_bytes_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Allocations Size"
      }
     ]
    },
    {
     "title": "Heap Generations (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(process_runtime_dotnet_gc_objects_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Fragmentation (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(process_runtime_dotnet_gc_heap_fragmentation_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC Collections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "idelta(process_runtime_dotnet_gc_collections_count_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(process_runtime_dotnet_exceptions_count_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Exceptions"
      }
     ]
    },
    {
     "title": "ThreadPool Threads",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(process_runtime_dotnet_thread_pool_threads_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "ThreadPool Threads"
      }
     ]
    },
    {
     "title": "ThreadPool Threads Queue Length",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(process_runtime_dotnet_thread_pool_queue_length{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "ThreadPool Threads Queue Length"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Responses Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_status_code!~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "  topk(10,\r\n  sum by (http_route, http_request_method, method_route) (\r\n    label_join(max_over_time(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_route!=\"\"}[$__rate_interval]), \"method_route\", \" \", \"http_request_method\", \"http_route\")\r\n  ))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "HTTP Method Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_request_method) (rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "sum(kestrel_active_connections{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}